### ISSUE TITLE
REST API not started properly

### ISSUE THREAD

**Issue by rollno748** [delirius325/jmeter-live-changes-config#13]
I have the script placed in the place but still observing this error

2019-04-16 16:39:33,880 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-04-16 16:39:33,881 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-04-16 16:39:33,881 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-04-16 16:39:33,898 INFO o.a.j.s.SaveService: Loading file: /home/ibrahim/null
2019-04-16 16:39:33,899 WARN o.j.r.p.TestPlanAnalyzer: Failed read jmx file
java.io.FileNotFoundException: /home/mibrahim/null (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_191]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_191]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_191]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.readBytesFromFile(TestPlanAnalyzer.java:64) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.getNodeListWithClassNames(TestPlanAnalyzer.java:103) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.analyze(TestPlanAnalyzer.java:33) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.analyzeTestPlan(PluginSuggester.java:51) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.findPluginsToInstall(PluginSuggester.java:44) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.checkAndSuggest(PluginSuggester.java:28) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.logging.LoggerAppender.append(LoggerAppender.java:33) [jmeter-plugins-manager-1.3.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2019) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1890) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184) [log4j-slf4j-impl-2.11.0.jar:2.11.0]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:431) [ApacheJMeter_core.jar:5.0 r1840935]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.startServer(LiveChanges.java:178) [jmeter.config.livechanges-0.0.2.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testStarted(LiveChanges.java:49) [jmeter.config.livechanges-0.0.2.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-04-16 16:39:33,933 WARN o.j.r.p.TestPlanAnalyzer: Cannot parse file: /home/mibrahim/null
org.xml.sax.SAXParseException: Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[?:1.8.0_191]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.getNodeListWithClassNames(TestPlanAnalyzer.java:104) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.analyze(TestPlanAnalyzer.java:33) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.analyzeTestPlan(PluginSuggester.java:51) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.findPluginsToInstall(PluginSuggester.java:44) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.checkAndSuggest(PluginSuggester.java:28) [jmeter-plugins-manager-1.3.jar:?]
	at org.jmeterplugins.repository.logging.LoggerAppender.append(LoggerAppender.java:33) [jmeter-plugins-manager-1.3.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) [log4j-core-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2019) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1890) [log4j-api-2.11.0.jar:2.11.0]
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184) [log4j-slf4j-impl-2.11.0.jar:2.11.0]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:431) [ApacheJMeter_core.jar:5.0 r1840935]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.startServer(LiveChanges.java:178) [jmeter.config.livechanges-0.0.2.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testStarted(LiveChanges.java:49) [jmeter.config.livechanges-0.0.2.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-04-16 16:39:33,934 ERROR i.g.d.j.c.l.LiveChanges: An error occured when loading the test plan tree. View JMeter's console for more information.
2019-04-16 16:39:33,936 INFO o.a.j.p.j.t.JavaTest: Created class: org.apache.jmeter.protocol.java.test.JavaTest. Uses tearDownTest: false
2019-04-16 16:39:33,936 INFO o.a.j.p.j.t.JavaTest: Created class: org.apache.jmeter.protocol.java.test.JavaTest. Uses tearDownTest: false
2019-04-16 16:39:33,937 INFO o.a.j.p.j.t.JavaTest: Created class: org.apache.jmeter.protocol.java.test.JavaTest. Uses tearDownTest: false
2019-04-16 16:39:33,937 INFO o.a.j.p.j.t.JavaTest: Created class: org.apache.jmeter.protocol.java.test.JavaTest. Uses tearDownTest: false
2019-04-16 16:39:33,993 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2019-04-16 16:39:34,245 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2019-04-16 16:39:34,245 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2019-04-16 16:39:34,245 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-04-16 16:39:34,246 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 perThread=1000.0 delayedStart=false
2019-04-16 16:39:34,258 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-04-16 16:39:34,258 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2019-04-16 16:39:34,284 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2019-04-16 16:58:26,446 INFO o.a.j.g.a.Start: Stopping test
2019-04-16 16:58:26,464 INFO o.a.j.t.JMeterThread: Stopping: Thread Group 1-1
2019-04-16 16:58:26,464 WARN o.a.j.t.JMeterThread: Interrupting: Thread Group 1-1 sampler: Java Request3
2019-04-16 16:58:26,471 WARN o.a.j.p.j.t.JavaTest: JavaTest: interrupted.
2019-04-16 16:58:26,474 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2019-04-16 16:58:26,476 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2019-04-16 16:58:26,478 ERROR i.g.d.j.c.l.LiveChanges: Unable to correctly shutdown Jetty server
java.lang.NullPointerException: null
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.finalizeTest(LiveChanges.java:193) [jmeter.config.livechanges-0.0.2.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testEnded(LiveChanges.java:64) [jmeter.config.livechanges-0.0.2.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:227) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:495) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-04-16 16:58:26,479 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by delirius325** [comment]
There seems to be some sort of error happening with 
`private static final String testPlanFile = String.format("%s/%s", FileServer.getFileServer().getBaseDir(), FileServer.getFileServer().getScriptName());` 

Could I get a screenshot of your `Test Plan` and of an `ls -l` of the directory where your script is located (if that's possible).

Thanks,

**Comment by rollno748** [comment]
Hi,
Please find the screenshot attached

Thanks
![ls-l](https://user-images.githubusercontent.com/18440913/56220080-7452a180-6085-11e9-8c7a-5b23d0c0177f.png)
![TestPlan](https://user-images.githubusercontent.com/18440913/56220082-74eb3800-6085-11e9-8663-f33c70128245.png)

**Comment by delirius325** [comment]
Hi and sorry for the late response,

I'm not sure if this issue is related to the plugin itself or the PluginsManager's `TestAnalyzer.java` class. I fail to see how the following line of code would return "null" for the current script.

`private static final String testPlanFile = String.format("%s/%s", FileServer.getFileServer().getBaseDir(), FileServer.getFileServer().getScriptName());`

Would it be possible for you to try this in a fresh JMeter install, free of the PluginsManager?

Thanks!
