### ISSUE TITLE
java.lang.IllegalArgumentException: No selectors

### ISSUE THREAD

**Issue by Kitty2014** [delirius325/jmeter-live-changes-config#14]
2019-05-03 22:13:24,873 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-05-03 22:13:24,879 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.IllegalArgumentException: No selectors
	at org.eclipse.jetty.io.SelectorManager.<init>(SelectorManager.java:78) ~[jetty-io-9.1.1.v20140108.jar:9.1.1.v20140108]
	at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.<init>(ServerConnector.java:532) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.ServerConnector.newSelectorManager(ServerConnector.java:227) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:220) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:94) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.Server.<init>(Server.java:107) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.api.App.<init>(App.java:19) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.startServer(LiveChanges.java:59) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testStarted(LiveChanges.java:28) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.github.delirius325.jmeter.config.livechanges.TestLiveChangesBackend
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.845 sec <<< FAILURE! - in io.github.delirius325.jmeter.config.livechanges.TestLiveChangesBackend
testServerConnectivity  Time elapsed: 0.788 sec  <<< ERROR!
com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7567 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at io.github.delirius325.jmeter.config.livechanges.TestLiveChangesBackend.testServerConnectivity(TestLiveChangesBackend.java:33)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7567 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at io.github.delirius325.jmeter.config.livechanges.TestLiveChangesBackend.testServerConnectivity(TestLiveChangesBackend.java:33)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at io.github.delirius325.jmeter.config.livechanges.TestLiveChangesBackend.testServerConnectivity(TestLiveChangesBackend.java:33)

Running io.github.delirius325.jmeter.config.livechanges.TestAppServer
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.752 sec - in io.github.delirius325.jmeter.config.livechanges.TestAppServer

Results :

Tests in error: 
  TestLiveChangesBackend.testServerConnectivity:33 » Unirest org.apache.http.con...

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

**Comment by Kitty2014** [comment]
how to  start localhost:7567 or localhost:8080
just run the jmeter ,did any backen server need to start?

**Comment by Kitty2014** [comment]
@delirius325  can this can be used [DummySampler](https://jmeter-plugins.org/wiki/DummySampler/?utm_source=jmeter&utm_medium=helplink&utm_campaign=DummySampler) to add which your config 
or buid a docker to simulate the environment
