### ISSUE TITLE
No Live Changes Config option under Config Element

### ISSUE THREAD

**Issue by QAInsights** [delirius325/jmeter-live-changes-config#19]
Hi, 

I am not seeing the Live Config element after placing the JAR in the ext folder in JMeter 5.3. Am I missing something here? 

![image](https://user-images.githubusercontent.com/2826376/83339678-e6a13800-a2bf-11ea-8180-673858db1b1a.png)

**Comment by QAInsights** [comment]
![image](https://user-images.githubusercontent.com/2826376/83339706-046e9d00-a2c0-11ea-8a83-00924fb192d3.png)

**Comment by delirius325** [comment]
Hi! Could I see the log from the console and the terminal?

Thanks!

**Comment by QAInsights** [comment]
Sure.

**Comment by QAInsights** [comment]
JMeter Log
```
2020-05-30 18:01:50,081 INFO o.a.j.u.JMeterUtils: Setting Locale to en_EN
2020-05-30 18:01:50,099 INFO o.a.j.JMeter: Loading user properties from: user.properties
2020-05-30 18:01:50,099 INFO o.a.j.JMeter: Loading system properties from: system.properties
2020-05-30 18:01:50,101 INFO o.a.j.JMeter: Copyright (c) 1998-2020 The Apache Software Foundation
2020-05-30 18:01:50,101 INFO o.a.j.JMeter: Version 5.3
2020-05-30 18:01:50,101 INFO o.a.j.JMeter: java.version=1.8.0_251
2020-05-30 18:01:50,102 INFO o.a.j.JMeter: java.vm.name=Java HotSpot(TM) Client VM
2020-05-30 18:01:50,102 INFO o.a.j.JMeter: os.name=Windows 10
2020-05-30 18:01:50,102 INFO o.a.j.JMeter: os.arch=x86
2020-05-30 18:01:50,102 INFO o.a.j.JMeter: os.version=10.0
2020-05-30 18:01:50,102 INFO o.a.j.JMeter: file.encoding=Cp1252
2020-05-30 18:01:50,103 INFO o.a.j.JMeter: java.awt.headless=null
2020-05-30 18:01:50,103 INFO o.a.j.JMeter: Max memory     =1073741824
2020-05-30 18:01:50,103 INFO o.a.j.JMeter: Available Processors =4
2020-05-30 18:01:50,109 INFO o.a.j.JMeter: Default Locale=English (EN)
2020-05-30 18:01:50,110 INFO o.a.j.JMeter: JMeter  Locale=English (EN)
2020-05-30 18:01:50,110 INFO o.a.j.JMeter: JMeterHome=C:\Tools\apache-jmeter-5.3
2020-05-30 18:01:50,110 INFO o.a.j.JMeter: user.dir  =C:\Tools\apache-jmeter-5.3\bin
2020-05-30 18:01:50,110 INFO o.a.j.JMeter: PWD       =C:\Tools\apache-jmeter-5.3\bin
2020-05-30 18:01:50,115 INFO o.a.j.JMeter: IP: 192.0.2.43 Name: DESKTOP-1234567 FullName: DESKTOP-1234567
2020-05-30 18:01:50,220 INFO o.a.j.JMeter: Setting LAF to: com.github.weisj.darklaf.DarkLaf:com.github.weisj.darklaf.theme.IntelliJTheme
2020-05-30 18:01:50,454 INFO o.a.j.JMeter: Loaded icon properties from org/apache/jmeter/images/icon.properties
2020-05-30 18:01:56,190 INFO o.j.r.JARSourceHTTP: Found cached repo
2020-05-30 18:01:56,345 INFO o.j.r.PluginManager: Plugins Status: [jpgc-graphs-basic=2.0, jpgc-graphs-additional=2.0, jpgc-dummy=0.4, jpgc-plugins-manager=1.4, bzm-random-csv=0.6, jmeter-core=5.3, jmeter-ftp=5.3, jmeter-http=5.3, jmeter-jdbc=5.3, jmeter-jms=5.3, jmeter-junit=5.3, jmeter-java=5.3, jmeter-ldap=5.3, jmeter-mail=5.3, jmeter-mongodb=5.3, jmeter-native=5.3, jmeter-tcp=5.3, jmeter-components=5.3]
2020-05-30 18:02:10,341 INFO o.a.j.s.FileServer: Default base='C:\Tools\apache-jmeter-5.3\bin'
2020-05-30 18:02:10,345 INFO o.a.j.g.a.Load: Loading file: C:\Tools\apache-jmeter-5.3\bin\Example_Ext.jmx
2020-05-30 18:02:10,345 INFO o.a.j.s.FileServer: Set new base='C:\Tools\apache-jmeter-5.3\bin'
2020-05-30 18:02:10,481 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2020-05-30 18:02:10,503 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2020-05-30 18:02:10,504 WARN o.a.j.s.SaveService: Can't register a converter: com.ubikingenierie.jmeter.plugin.videostreaming.result.HTTPSampleResultChunkConverter
java.lang.ClassNotFoundException: com.ubikingenierie.jmeter.plugin.videostreaming.result.HTTPSampleResultChunkConverter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:284) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:259) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.initProps(SaveService.java:245) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:164) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.LoadRecentProject.doActionAfterCheck(LoadRecentProject.java:66) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
2020-05-30 18:02:10,510 WARN o.a.j.s.SaveService: Can't register a converter: com.ubikingenierie.jmeter.plugin.videostreaming.result.HTTPSampleResultManifestConverter
java.lang.ClassNotFoundException: com.ubikingenierie.jmeter.plugin.videostreaming.result.HTTPSampleResultManifestConverter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:284) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:259) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.initProps(SaveService.java:245) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:164) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.LoadRecentProject.doActionAfterCheck(LoadRecentProject.java:66) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
2020-05-30 18:02:10,511 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2020-05-30 18:02:10,512 WARN o.a.j.s.SaveService: Can't register a converter: com.ubikingenierie.jmeter.plugin.videostreaming.result.VideoStreamingSampleResultConverter
java.lang.ClassNotFoundException: com.ubikingenierie.jmeter.plugin.videostreaming.result.VideoStreamingSampleResultConverter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:284) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:259) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.initProps(SaveService.java:245) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:164) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.LoadRecentProject.doActionAfterCheck(LoadRecentProject.java:66) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
2020-05-30 18:02:10,513 WARN o.a.j.s.SaveService: Can't register a converter: com.blazemeter.jmeter.citrix.sampler.CitrixSampleResultConverter
java.lang.ClassNotFoundException: com.blazemeter.jmeter.citrix.sampler.CitrixSampleResultConverter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:284) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.registerConverter(SaveService.java:259) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.initProps(SaveService.java:245) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.save.SaveService.<clinit>(SaveService.java:164) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.LoadRecentProject.doActionAfterCheck(LoadRecentProject.java:66) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
2020-05-30 18:02:10,514 INFO o.a.j.s.SaveService: Loading file: C:\Tools\apache-jmeter-5.3\bin\Example_Ext.jmx
2020-05-30 18:02:10,645 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-05-30 18:02:10,645 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-05-30 18:02:10,645 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-05-30 18:02:10,645 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-05-30 18:02:10,645 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2020-05-30 18:02:10,645 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2020-05-30 18:02:10,798 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2020-05-30 18:02:10,798 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2020-05-30 18:02:10,798 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2020-05-30 18:02:10,799 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2020-05-30 18:02:11,202 INFO o.a.j.s.FileServer: Set new base='C:\Tools\apache-jmeter-5.3\bin'
```

**Comment by QAInsights** [comment]
No error in the console.
![image](https://user-images.githubusercontent.com/2826376/83339897-ac389a80-a2c1-11ea-8902-f7b85f4b102f.png)

**Comment by delirius325** [comment]
Do you mind removing the plugins which are causing errors in the JMeter log and see if you see the Live Changes Config show after that? Might be a conflict between JARs

**Comment by QAInsights** [comment]
Yes, I tried that already. I removed the plugins, but Live Changes are not showing up :(

**Comment by delirius325** [comment]
Can you try with a freshly downloaded JMeter? Clean of all other things?

**Comment by QAInsights** [comment]
I did a fresh install. I am not seeing the option :(. Below is the log.

```
2020-05-30 18:24:54,251 INFO o.a.j.u.JMeterUtils: Setting Locale to en_EN
2020-05-30 18:24:54,295 INFO o.a.j.JMeter: Loading user properties from: user.properties
2020-05-30 18:24:54,307 INFO o.a.j.JMeter: Loading system properties from: system.properties
2020-05-30 18:24:54,310 INFO o.a.j.JMeter: Copyright (c) 1998-2020 The Apache Software Foundation
2020-05-30 18:24:54,310 INFO o.a.j.JMeter: Version 5.3
2020-05-30 18:24:54,310 INFO o.a.j.JMeter: java.version=1.8.0_251
2020-05-30 18:24:54,310 INFO o.a.j.JMeter: java.vm.name=Java HotSpot(TM) Client VM
2020-05-30 18:24:54,310 INFO o.a.j.JMeter: os.name=Windows 10
2020-05-30 18:24:54,310 INFO o.a.j.JMeter: os.arch=x86
2020-05-30 18:24:54,311 INFO o.a.j.JMeter: os.version=10.0
2020-05-30 18:24:54,317 INFO o.a.j.JMeter: file.encoding=Cp1252
2020-05-30 18:24:54,318 INFO o.a.j.JMeter: java.awt.headless=null
2020-05-30 18:24:54,318 INFO o.a.j.JMeter: Max memory     =1073741824
2020-05-30 18:24:54,318 INFO o.a.j.JMeter: Available Processors =4
2020-05-30 18:24:54,325 INFO o.a.j.JMeter: Default Locale=English (EN)
2020-05-30 18:24:54,326 INFO o.a.j.JMeter: JMeter  Locale=English (EN)
2020-05-30 18:24:54,326 INFO o.a.j.JMeter: JMeterHome=C:\Tools\Temp\apache-jmeter-5.3
2020-05-30 18:24:54,326 INFO o.a.j.JMeter: user.dir  =C:\Tools\Temp\apache-jmeter-5.3\bin
2020-05-30 18:24:54,327 INFO o.a.j.JMeter: PWD       =C:\Tools\Temp\apache-jmeter-5.3\bin
2020-05-30 18:24:54,329 INFO o.a.j.JMeter: IP: 192.0.2.43 Name: DESKTOP-789466 FullName: DESKTOP-789466
2020-05-30 18:24:54,441 INFO o.a.j.JMeter: Setting LAF to: com.github.weisj.darklaf.DarkLaf:com.github.weisj.darklaf.theme.IntelliJTheme
2020-05-30 18:24:54,676 INFO o.a.j.JMeter: Loaded icon properties from org/apache/jmeter/images/icon.properties

```
![image](https://user-images.githubusercontent.com/2826376/83340180-a2fcfd00-a2c4-11ea-8d8a-ef1ffe6136b5.png)

**Comment by delirius325** [comment]
This might be a longshot, but do you mind trying with a version of Java higher than 1.8?

**Comment by QAInsights** [comment]
I am using latest version of Java.
![image](https://user-images.githubusercontent.com/2826376/83341730-4efb1400-a2d6-11ea-8fe8-84ce90ff57bc.png)

**Comment by delirius325** [comment]
Java version 1.8.0 is quite old, your other plugins error in logs were also produced by the fact that you are using an older version of Java. Try updating to at least 1.9.0, I'm personally using OpenJDK 1.13.

**Comment by QAInsights** [comment]
Actually I installed from Java website, still installed older version :). Then I installed using `winget`, it installed OpenJDK 14. Now it is showing up. Closing this issue. Thanks!
