### ISSUE TITLE
Is webbitserver a long-term choice

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-live-changes-config#2]
Hello,
What are your reasons for selecting it ? I am very interested by your feedback.
I am just wondering if webbitserver is a long-term choice, it looks like it still relies on netty 3.5.5 ?
And webbit-rest is pretty young 0.2.0.
Would undertow (http://undertow.io/) or Jetty (which seems one of the most embeddded ones) not be a better choice in the long term ?

Just my 2 cents of course
Thanks
Regards

**Comment by delirius325** [comment]
Hey!

It's funny that you are mentioning this. Yesterday while looking at my code I was actually planning on switching it to Jetty or another server. I mostly chose them for their familiarity in syntax - when developing web servers/apis I usually work with Express in Node.JS. 

I agree that webbit doesn't look like a good choice for the long term. It'll most likely be changed in the next ALPHA version of the plugin. I also didn't know about undertow, I'll look it up 😄 !

Thanks for the quick feedback!

**Comment by delirius325** [comment]
Note to self:

Jetty is working fine when used within my unit tests. Throws "NoSuchMethod" when using within JMeter.

```log
2019-02-20 14:29:17,362 WARN o.e.j.u.SharedBlockingCallback: Blocker not complete Blocker@2791f45e{null}
2019-02-20 14:29:17,365 WARN o.e.j.s.HttpChannel: /api/test/connectivity
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: org.eclipse.jetty.server.Connector.isShutdown()Z
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:432) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:502) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) [jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) [jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: org.eclipse.jetty.server.Connector.isShutdown()Z
	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:460) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:285) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416) ~[jmeter.config.livechanges-0.0.2.jar:?]
	... 23 more
Caused by: java.lang.NoSuchMethodError: org.eclipse.jetty.server.Connector.isShutdown()Z
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:723) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:690) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:548) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:845) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:921) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:250) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:226) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:551) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:325) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167) ~[?:?]
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:302) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:256) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:271) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:848) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:413) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:734) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:280) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703) ~[jmeter.config.livechanges-0.0.2.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416) ~[jmeter.config.livechanges-0.0.2.jar:?]
	... 23 more
```

**Comment by delirius325** [comment]
It seems like this would be a dependency issue. Currently looking into it.
